development:
  adapter: postgresql
  encoding: unicode
  database: keroauc_development
  host: localhost
  pool: 5
  username:
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: keroauc_test
  host: localhost
  pool: 5
  username:
  password:
